name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-huggingface:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server/imagepro-file-process
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0
        with:
          ssh-private-key: ${{ secrets.HF_SSH_KEY }}

      # Configure Git user
      - name: Configure Git user
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      # Initialize Git repository in subdirectory
      - name: Initialize Git repository
        run: |
          git init
          git remote add origin git@hf.co:spaces/jacksonkasi/imagepro-file-process.git

      # Disable strict host key checking
      - name: Disable strict host key checking
        run: |
          echo -e "Host hf.co\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # Add and commit files
      - name: Add and commit files
        run: |
          git add .
          git commit -m "Deploy to Hugging Face Space"

      # Push to Hugging Face Space
      - name: Push to Hugging Face Space
        run: |
          git push -u origin main --force
