name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Set up SSH key
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.HF_SSH_KEY }}

      # Add Hugging Face Space as a remote named 'space'
      - name: Add Hugging Face remote
        run: |
          git remote add space git@hf.co:spaces/jacksonkasi/imagepro-file-process.git

      # Push the code to Hugging Face Space
      - name: Push to Hugging Face Space
        run: |
          git push --force space main
